name: Package VSIX

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: |
          cd client
          npm install
          mkdir out
          TARGET_OS=windows TARGET_ARCH=amd64 npx vsce package -t linux-x64 -o vls-linux.vsix
          rm out/*
          TARGET_OS=windows TARGET_ARCH=amd64 npx vsce package -t win32-x64 -o vls-windows.vsix
          rm out/*
          TARGET_OS=windows TARGET_ARCH=amd64 npx vsce package -t darwin-x64 -o vls-darwin.vsix

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v3
        with:
          name: vls-linux-amd64
          path: client/vls-linux.vsix

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: vls-windows-amd64
          path: client/vls-windows.vsix

      - name: Upload Darwin Artifact
        uses: actions/upload-artifact@v3
        with:
          name: vls-darwin-amd64
          path: client/vls-macos.vsix
